stages:
  - build

build_frontend:
  stage: build
  tags:
    - windows
  script:
    - echo "--- Bat dau Build Frontend ---"
    # Dùng đường dẫn đầy đủ tuyệt đối từ thư mục gốc của project
    # Thay vì 'cd', hãy gọi trực tiếp lệnh npm trong thư mục đích bằng cách dùng chuỗi đường dẫn
    - $frontendDir = Join-Path -Path $env:CI_PROJECT_DIR -ChildPath "Front-End-ReactJS"
    - Set-Location -Path $frontendDir
    - npm install
    - npm run build

build_backend:
  stage: build
  tags:
    - windows
  script:
    - echo "--- Bat dau Build Backend ---"
    - $backendDir = Join-Path -Path $env:CI_PROJECT_DIR -ChildPath "Back-End-ASP.Net/ResUpClub.API"
    - Set-Location -Path $backendDir
    - dotnet build "ResUpClubWebAPI.sln" --configuration Release