stages:
  - build

build_frontend:
  stage: build
  tags:
    - windows
  script:
    - echo "--- Checking directory ---"
    - dir
    - echo "--- Building Frontend ---"
    # Kiểm tra xem thư mục có thực sự tồn tại ở đây không
    - cd "Front-End-ReactJS"
    - npm install
    - npm run build

build_backend:
  stage: build
  tags:
    - windows
  script:
    - echo "--- Building Backend ---"
    - cd "Back-End-ASP.Net/ResUpClub.API"
    # Sử dụng lệnh dir để xem file .sln có thực sự ở đây không
    - dir
    - dotnet build "ResUpClubWebAPI.sln" --configuration Release